
CREATE TABLE LOCATAIRES 
(
CODE_LOCATAIRE INTEGER	NOT NULL PRIMARY KEY ,
NOM VARCHAR(50) NOT NULL ,
PRENOM VARCHAR(50) NOT NULL ,
AGE INTEGER CHECK (AGE BETWEEN 18 AND 70) ,
MAIL VARCHAR(50) UNIQUE CHECK (MAIL LIKE '%@%.%'),
DATE_LOCATION DATE DEFAULT GETDATE() ,
ADRESSE VARCHAR(50) NOT NULL ,
DEPARTEMENT INTEGER CHECK (DEPARTEMENT BETWEEN 1 AND 95)
);


CREATE TABLE MAISONS 
(
NUM_MAISON INTEGER NOT NULL PRIMARY KEY ,
CODE_LOCATAIRE INTEGER NOT NULL FOREIGN KEY 
REFERENCES LOCATAIRES (CODE_LOCATAIRE),
NBR_CHAMBRE INTEGER NOT NULL ,
SURFACE FLOAT CHECK (SURFACE BETWEEN 30 AND 150)
);


